spring.datasource.url=jdbc:postgresql://localhost:5432/pedidoFeitoDb
spring.datasource.username=pedidoFeitoAdmin
spring.datasource.password=pedidofeito123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true